In [16]:
#Importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn as sk
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

In [22]:
#Importing the training dataset
globalHealthDataFrame= pd.read_csv('s3://rmit-ml-2020s1-lab-data/Assignment1_data/train.csv',
            delimiter=',')

In [23]:
#Importing the testing dataset
test_globalHealthDataFrame= pd.read_csv('s3://rmit-ml-2020s1-lab-data/Assignment1_data/test.csv',
            delimiter=',')

In [25]:
#Removing ID column from the training & testing daraframe
modified_globalHealthDataFrame = globalHealthDataFrame.drop(['ID'], axis=1)
test_globalHealthDataFrame = test_globalHealthDataFrame.drop(['ID'], axis=1)

In [20]:
modified_globalHealthDataFrame.describe()

,Country,Year,Status,AdultMortality,AdultMortality-Male,AdultMortality-Female,InfantDeaths,Alcohol,PercentageExpenditure,Measles,...,Polio,TotalExpenditure,Diphtheria,HIV-AIDS,GDP,Population,Thinness1-19years,Thinness5-9years,IncomeCompositionOfResources,Schooling
count,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,...,867.000000,867.000000,867.000000,867.000000,867.000000,8.670000e+02,867.000000,867.000000,867.000000,867.000000
mean,97.908881,2009.519031,0.147636,168.310265,167.351788,169.268743,23.673587,4.323230,675.455038,3193.158016,...,81.675894,5.926228,80.869666,2.002999,6768.605686,4.977211e+06,4.458247,4.474740,0.638852,3.444089
std,59.047382,4.615772,0.354943,136.148089,136.339678,136.521130,54.762901,3.624657,1742.603943,14422.950469,...,24.150902,2.287944,25.153943,5.716692,14405.688854,1.069932e+07,3.614439,3.704803,0.185802,0.538432
min,1.000000,2002.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.010000,0.000000,0.000000,...,3.000000,1.120000,3.000000,0.100000,4.130000,1.350000e+02,0.100000,0.100000,0.000000,0.000000
25%,41.000000,2006.000000,0.000000,71.000000,68.000000,72.000000,0.000000,1.155000,2.005443,0.000000,...,78.500000,4.325000,78.000000,0.100000,413.730000,1.274450e+05,1.400000,1.400000,0.483000,3.154352
50%,104.000000,2010.000000,0.000000,143.000000,140.000000,144.000000,2.000000,3.240000,60.341451,13.000000,...,92.000000,5.830000,91.000000,0.100000,1272.850000,3.331430e+05,3.500000,3.400000,0.677000,3.535534
75%,155.000000,2014.000000,0.000000,224.000000,223.000000,226.000000,23.500000,7.435000,466.703840,243.000000,...,97.000000,7.500000,97.000000,0.600000,4755.220000,3.253793e+06,6.800000,6.700000,0.778500,3.781534
max,191.000000,2017.000000,1.000000,723.000000,742.000000,778.000000,490.000000,13.200000,11734.853810,182485.000000,...,99.000000,11.790000,99.000000,43.500000,99192.600000,5.414673e+07,16.300000,19.100000,0.937000,4.549725

In [26]:
test_globalHealthDataFrame.describe()

,Country,Year,Status,AdultMortality,AdultMortality-Male,AdultMortality-Female,InfantDeaths,Alcohol,PercentageExpenditure,Measles,...,Polio,TotalExpenditure,Diphtheria,HIV-AIDS,GDP,Population,Thinness1-19years,Thinness5-9years,IncomeCompositionOfResources,Schooling
count,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,...,867.000000,867.000000,867.000000,867.000000,867.000000,8.670000e+02,867.000000,867.000000,867.000000,867.000000
mean,97.908881,2009.519031,0.147636,168.310265,167.351788,169.268743,23.673587,4.323230,675.455038,3193.158016,...,81.675894,5.926228,80.869666,2.002999,6768.605686,4.977211e+06,4.458247,4.474740,0.638852,3.444089
std,59.047382,4.615772,0.354943,136.148089,136.339678,136.521130,54.762901,3.624657,1742.603943,14422.950469,...,24.150902,2.287944,25.153943,5.716692,14405.688854,1.069932e+07,3.614439,3.704803,0.185802,0.538432
min,1.000000,2002.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.010000,0.000000,0.000000,...,3.000000,1.120000,3.000000,0.100000,4.130000,1.350000e+02,0.100000,0.100000,0.000000,0.000000
25%,41.000000,2006.000000,0.000000,71.000000,68.000000,72.000000,0.000000,1.155000,2.005443,0.000000,...,78.500000,4.325000,78.000000,0.100000,413.730000,1.274450e+05,1.400000,1.400000,0.483000,3.154352
50%,104.000000,2010.000000,0.000000,143.000000,140.000000,144.000000,2.000000,3.240000,60.341451,13.000000,...,92.000000,5.830000,91.000000,0.100000,1272.850000,3.331430e+05,3.500000,3.400000,0.677000,3.535534
75%,155.000000,2014.000000,0.000000,224.000000,223.000000,226.000000,23.500000,7.435000,466.703840,243.000000,...,97.000000,7.500000,97.000000,0.600000,4755.220000,3.253793e+06,6.800000,6.700000,0.778500,3.781534
max,191.000000,2017.000000,1.000000,723.000000,742.000000,778.000000,490.000000,13.200000,11734.853810,182485.000000,...,99.000000,11.790000,99.000000,43.500000,99192.600000,5.414673e+07,16.300000,19.100000,0.937000,4.549725

In [5]:
#Define X(input) Y(Output) variables
X = modified_globalHealthDataFrame[modified_globalHealthDataFrame.columns[1:23]]
Y = modified_globalHealthDataFrame[['TARGET_LifeExpectancy']]

In [27]:
test_X = test_globalHealthDataFrame[test_globalHealthDataFrame.columns[0:22]]

In [37]:
pd.isna(test_globalHealthDataFrame).sum()

Country                         0
Year                            0
Status                          0
AdultMortality                  0
AdultMortality-Male             0
AdultMortality-Female           0
InfantDeaths                    0
Alcohol                         0
PercentageExpenditure           0
Measles                         0
BMI                             0
UnderFiveDeaths                 0
Polio                           0
TotalExpenditure                0
Diphtheria                      0
HIV-AIDS                        0
GDP                             0
Population                      0
Thinness1-19years               0
Thinness5-9years                0
IncomeCompositionOfResources    0
Schooling                       0
dtype: int64

In [6]:
from sklearn import model_selection
number_splits = 10
kFold = model_selection.KFold(n_splits=number_splits, shuffle=True)

In [11]:
# Create a polynomial regression of degree 2
from sklearn.preprocessing import PolynomialFeatures
polyFeat = PolynomialFeatures(degree=2, include_bias=True)

In [43]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

# plt.figure()
# lResults = np.zeros((number_splits,len(lRegPara)))
nsplit = 0
Total_MSE = 0
Total_MAE = 0
Total_r2 = 0

for trainIndex, validIndex in kFold.split(X):
    # Get the training and validation data
    trainX = np.array(X.loc[trainIndex])
    trainY = np.array(Y.loc[trainIndex])
    validX = np.array(X.loc[validIndex])
    validY = np.array(Y.loc[validIndex])
    
    polyFitTrainX = polyFeat.fit_transform(trainX)
    polyFitValidX = polyFeat.fit_transform(validX)
    
    polyRidgeReg = linear_model.Lasso(alpha=0.025, normalize=False)
    polyRidgeReg.fit(polyFitTrainX, trainY)
    predY = polyRidgeReg.predict(polyFitValidX)
    np.savetxt("result.csv", predY, delimiter=",")
    
    mse = mean_squared_error(validY, predY)
    mae = mean_absolute_error(validY, predY)
    r2 = r2_score(validY, predY)
    Total_MSE = Total_MSE + mse
    Total_MAE = Total_MAE + mae
    Total_r2 = Total_r2 + r2

print(polyFitValidX.shape)
print(Total_MSE/10)
print(Total_MAE/10)
print(Total_r2/10)

KeyError: "None of [Int64Index([   0,   14,   18,   56,   76,   94,  104,  114,  119,  126,\n            ...\n            2007, 2013, 2037, 2039, 2050, 2052, 2053, 2066, 2068, 2069],\n           dtype='int64', length=208)] are in the [columns]"